
service: service

provider:
  name: aws
  runtime: nodejs4.3

functions:
  listings:
    handler: handler.listings
    events:
      - http:
          method: get
          path: listings
          cors: true
  reserve:
    handler: handler.reserve
    events:
      - http:
          method: post
          path: reserve
          cors: true
  provision:
    handler: handler.provision
    events: 
      - http:
          method: post
          path: provision
          cors: true
  availability:
    handler: handler.availability
    events:
      - http:
          method: get
          path: provision
          cors: true