export const types = {
  FETCH_OPENTABLE_LIST: 'FETCH_OPENTABLE_LIST',
  PROVISION_OPENTABLE: 'PROVISION_OPENTABLE',
  RESERVE_OPENTABLE: 'RESERVE_OPENTABLE',
  AVAILABILITY_OPENTABLE: 'AVAILABILITY_OPENTABLE'
}